-- db/seed_products.sql — produtos do catálogo (rode depois do schema.sql)
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('curso','100kg – Domínio Absoluto','proprio',1,'{"controle","pressao","base","guarda","passagem","fundamentos","gi","nogi","iniciante","evergreen"}','conteúdo técnico/didático de controle, pressão, base ou leitura de jogo',null,'https://alohabjjnews.com/','',null,1.0,false,'Curso 100kg – Domínio Absoluto, grátis no link','Curso gratuito de jogo de pressão e controle — leva do conteúdo ao aprofundamento.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('bjj3d','Loja BJJ3D','proprio',2,'{"produto","loja","lifestyle","presente","marca"}','quando não há afiliado específico melhor e cabe um produto de marca própria',null,null,'',null,null,false,'🛒 Loja BJJ3D no link','Loja BJJ3D — produtos exclusivos pra quem vive o Jiu-Jitsu dentro e fora do tatame.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('hayabusa','Equipamento Hayabusa','afiliado',3,'{"equipamento","gear","kimono","luva","protecao","marca-parceira"}','pauta sobre equipamento/gear de alto desempenho em geral','hayabusa jiu jitsu',null,'LUCAS','-10%',null,true,'🥊 Hayabusa com cupom LUCAS -10% (parceria)','Equipamento Hayabusa de alto desempenho — cupom LUCAS -10%.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('gi-competicao','Kimono de competição (campeão de vendas)','afiliado',3,'{"gi","kimono","competicao","mundial","ibjjf","faixa-preta","absoluto"}','pauta de GI / campeonato IBJJF / final de Mundial / disputa no kimono','kimono jiu jitsu competição trançado',null,'',null,null,true,'🥋 Kimono de competição (parceria) — link','O kimono que aguenta um campeonato inteiro — resistência e caimento de competição.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('rashguard-nogi','Rashguard / gear No-Gi (campeão de vendas)','afiliado',3,'{"nogi","no-gi","adcc","grappling","rashguard","submission","superluta"}','pauta No-Gi / ADCC / superluta de grappling','rashguard jiu jitsu no gi manga longa',null,'',null,null,true,'Rashguard No-Gi (parceria) — link','Rashguard que segura pegada e suor numa guerra de No-Gi.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('instrucional-leglock','Instrucional de leg locks (campeão de vendas)','afiliado',3,'{"leglock","leg-lock","heelhook","heel-hook","ankle-lock","nogi","finalizacao","perna"}','pauta com leg lock / heel hook / finalização de perna',null,null,'',null,null,true,'📚 Instrucional de leg locks (parceria) — link','Aprofunde o jogo de perna com quem domina — instrucional dos melhores.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('instrucional-guarda','Instrucional de guarda/passagem (campeão de vendas)','afiliado',3,'{"guarda","passagem","de-la-riva","x-guard","meia-guarda","raspagem","gi","tecnica"}','breakdown técnico de guarda, passagem ou raspagem',null,null,'',null,null,true,'📚 Instrucional de guarda/passagem (parceria) — link','Sistematize sua guarda/passagem com um instrucional de referência.') on conflict (id) do nothing;
insert into products (id,nome,tipo,prioridade,tags,gatilho,busca,url_base,cupom,desconto,margem,disclosure_obrigatorio,cta_sugerido,gancho) values ('instrucional-costas','Instrucional de pegada nas costas / mata-leão (campeão de vendas)','afiliado',3,'{"costas","back-control","mata-leao","estrangulamento","finalizacao"}','pauta sobre pegada nas costas, mata-leão ou estrangulamento',null,null,'',null,null,true,'📚 Instrucional de costas/mata-leão (parceria) — link','Feche o jogo pelas costas com um sistema testado no alto nível.') on conflict (id) do nothing;
